include:
  - project: 'platform/pipelines-templates'
    file: '/build/mkdocs/template-documentation-site.yml'
    ref: 'master'

variables:
  IMAGE_NAME: core/documentation-site

deploy:
  variables:
    KUBE_URL: "${KUBE_TOOLS_URL}"
    KUBE_TOKEN: "${KUBE_TOOLS_TOKEN}"
    KUBE_CA_PEM: "${KUBE_TOOLS_CA_PEM}"
    KUBE_NAMESPACE: "console"
    ENVIRONMENT_PREFIX: "CLOUD_"
