include:
  - project: 'platform/pipelines-templates'
    file: '/build/node/template-react-yarn.yml'
    ref: master

test:
  script:
    - yarn lint
    # - ./node_modules/.bin/cspell "./docs/**" // TODO: re enable when services documentation are verified

variables:
  IMAGE_NAME: core/documentation-site

.docker-job:
  dependencies:
    - build-site

build-latest:
  only:
    - master
    - tags

build-site:
  only:
    - branches
    - tags

deploy-next:
  stage: deploy
  variables:
    ENVIRONMENT_TO_DEPLOY: PROD
  trigger:
    project: "clients/mia-platform/platform-documentation/configurations"
  only:
    refs:
      - master

deploy:
  stage: deploy
  variables:
    ENVIRONMENT_TO_DEPLOY: PROD
    DOCS_SITE_VERSION: $(echo ${CI_COMMIT_TAG} | sed s/^v//)
  trigger:
    project: "clients/mia-platform/platform-documentation/configurations"
  only:
    refs:
      - tags
