include:
  - project: 'platform/pipelines-templates'
    file: '/build/node/template-react-yarn.yml'
    ref: master

default:
  image: node:16.15.0-alpine

test:
  script:
    - yarn lint
    - npm run spellcheck
    - npm run check-content

variables:
  IMAGE_NAME: core/documentation-site

.docker-job:
  dependencies:
    - build-site

build-latest:
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

build-site:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

#deploy-preview:
#  stage: deploy
#  cache:
#    key: "${CI_COMMIT_REF_SLUG}"
#    paths:
#      - node_modules
#      - build
#    policy: pull
#  allow_failure: true
#  variables:
#    STATICDEPLOY_API_URL: ${STATICDEPLOY_API_URL}
#    STATICDEPLOY_API_TOKEN: ${STATICDEPLOY_API_TOKEN}
#    BUNDLE_NAME: 'platform-documentation'
#  script:
#    - ./node_modules/.bin/staticdeploy bundle --config ./staticdeploy.config.js
#    - ./node_modules/.bin/staticdeploy deploy --config ./staticdeploy.config.js
#  rules:
#    - if: $CI_COMMIT_TAG
#      when: never
#    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

deploy-next:
  stage: deploy
  variables:
    ENVIRONMENT_TO_DEPLOY: PROD
  trigger:
    project: "clients/mia-platform/platform-documentation/configurations"
  only:
    refs:
      - master

deploy:
  stage: deploy
  variables:
    ENVIRONMENT_TO_DEPLOY: PROD
    DOCS_SITE_VERSION: $(echo ${CI_COMMIT_TAG} | sed s/^v//)
  trigger:
    project: "clients/mia-platform/platform-documentation/configurations"
  only:
    refs:
      - tags
