site_name: Mia-Platform Docs
site_description: Platform documentation of Mia Platform
site_author: Mia Platform Team
copyright: Mia srl. All rights reserved.

nav:
- Home:
  - Mia Platform Docs: 'index.md'
  - Getting Started: 'getting_started/quickstart.md'
  - Design Guidelines: 'dev_ops_guide/git_vademecum.md'
  - Custom Plugin: 'development_suite/api-console/api-design/plugin_baas_4.md'
  - CMS and Analytics: 'business_suite/overview-business-suite.md'
  - DevOps: 'development_suite/monitoring-dashboard/dev_ops_guide/business_continuity.md'
  - Release Notes: 'release_notes/apiconsole_releasenotes.md'
  - Info: 'info/version-policy.md'

- Guidelines:
    - GIT Vademecum: 'dev_ops_guide/git_vademecum.md'
    - REST API Vademecum: 'guidelines/rest_api.md'
    - API: 'guidelines/api.md'
    - Microservices Vademecum: 'guidelines/microservice_vademecum.md'
    - Communication among Microservices: 'guidelines/communication_between_services_mp4.md'
    - Docker Vademecum: 'guidelines/docker_vademecum.md'

- Development Suite:
  - Overview: 'development_suite/overview-dev-suite.md'
  - API Console:
    - Access the API Console: 'development_suite/api-console/accedi_apiconsole.md'
    - API Design:
      - Create a CRUD 5'min: 'development_suite/api-console/api-design/quick_rest_api.md'
      - CRUD Section: 'development_suite/api-console/api-design/crud_advanced.md'
      - Manage your Microservices from the Api Console: 'development_suite/api-console/api-design/services.md'
      - Microservice from template - Get started: 'development_suite/api-console/api-design/custom_microservice_get_started.md'
      - Expose and manage the safety of an apis: 'development_suite/api-console/api-design/esponi_api.md'
      - Enrich your call with some Decorators: 'development_suite/api-console/api-design/decorators.md'
      - Configure CMS: 'development_suite/api-console/api-design/api_console_configcms.md'
      - Configure Analytics: 'development_suite/api-console/api-design/api_console_configanalytics.md'

    - Develop a Microservice:
      - Create a Node Custom Microservices: 'development_suite/api-console/api-design/plugin_baas_4.md'
      - Add a Microservices Template : 'development_suite/api-console/api-design/templates_conf.md'
      - Debug a Microservice:
        - Debugging a single service with Telepresence: 'development_suite/debugging/telepresence.md'

    - Advanced Section:
      - API Gateway:
        -  Create config map: 'development_suite/api-gateway-config-map.md'
        -  Request Size: 'development_suite/api-console/advanced-section/request-size.md'
      - API Console Config:
        - Change the name of Core Microservices: 'development_suite/api-console/advanced-section/advanced_name_core.md'
    - Deploy:
      - Release your configurations: 'development_suite/api-console/api-design/deploy.md'

  - API Portal:
    - Configure Swagger Aggregator: 'development_suite/api-portal/swagger_conf.md'

  - Monitoring Dashboard:
    - Business Continuity: 'development_suite/monitoring-dashboard/dev_ops_guide/business_continuity.md'
    - Disaster Recovery: 'development_suite/monitoring-dashboard/dev_ops_guide/disaster_recovery.md'
    - Autoscaling Pods: 'development_suite/monitoring-dashboard/dev_ops_guide/autoscaling.md'
    - Guidelines for logs: 'development_suite/monitoring-dashboard/dev_ops_guide/log.md'

- Runtime Suite:
    - Overview: 'runtime_suite/overview-runtime-suite.md'
    - API & Microservice Ecosystem:
       - API Gateway: 'runtime_suite/api-gateway.md'
       - Microservice Gateway: 'runtime_suite/microservice-gateway.md'
       - BaaS:
         - Crud: 'runtime_suite/crud-service.md'
         - Static File Hosting: 'runtime_suite/static-file-service.md'
         - File Manager Service: 'runtime_suite/files-service.md'
         - Notifications:
           - Push Notifications: 'runtime_suite/push_notifications_platform_4.md'
           - Mail Service: 'runtime_suite/mail-notification.md'
           - Notifcation Manager: 'runtime_suite/notifications-manager.md'
         - iOS SDK: 'runtime_suite/sdk_ios.md'
         - Android SDK: 'runtime_suite/sdk_android.md'
         - PDF Service: 'runtime_suite/pdf-service.md'
       - Data Management:
         - SQL Generic Reader: 'runtime_suite/sql-reader.md'
         - CQRS/Event Source Management: 'runtime_suite/event-source-management.md'
         - Secure Data Exchange Service: 'runtime_suite/secure-data-exchange-service.md'
         - Soap To Rest: 'runtime_suite/soap-to-rest.md'
       - API Automation:
         - Cronjobs Microservices: 'runtime_suite/cron.md'
    - Privacy & Security:
       - Access Management:
         - Auth Service: 'runtime_suite/auth-service.md'
         - Users Profile: 'runtime_suite/user-service.md'
         - ACL Service: 'runtime_suite/acl-service.md'
         - Session Manager: 'runtime_suite/session-manager.md'

- Business Suite:
  - Overview: 'business_suite/overview-business-suite.md'
  - CMS:
    - Use CMS: 'business_suite/guide_cms.md'
    - Configure CMS through API Console: 'development_suite/api-console/api-design/api_console_configcms.md'
    - Configure CMS .json file: 'business_suite/conf_cms.md'
    - Color CMS: 'business_suite/colorare_il_cms.md'
    - Update CMS: 'business_suite/update_cms.md'
    - Integrate custom frontends into the CMS: 'business_suite/custom-frontends-integration-CMS.md'

  - Analytics:
    - Configure Analytics through API Console: 'development_suite/api-console/api-design/api_console_configanalytics.md'
    - Configure Analytics .json file: 'business_suite/conf_analytics.md'

- Release Notes:
    - Platform: 'release_notes/platform_releasenotes.md'

- Info:
    - Version Policy: 'info/version-policy.md'
    - Open Source Software in Mia Platform: 'info/oss.md'
    - Audit Process: 'info/audit-process.md'
    - Subprocessor: 'info/subprocessor.md'
    - Installation Process: 'info/installation-process.md'
    - Bug Policy: 'info/bug-policy.md'



theme:
  name: 'material'
  logo: 'img/mia-platform-white.png'
  favicon: 'img/favicon.ico'
  language: 'it'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: 'true'
  extra:
    social:
      - type: globe
        link: https://www.mia-platform.eu/
      - type: linkedin
        link: https://www.linkedin.com/company/mia-platform/


google_analytics:
  - 'UA-122091925-1'
  - 'auto'
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
