site_name: Mia-Platform Docs
repo_url: https://git.tools.mia-platform.eu/platform/documentations
site_description: Platform documentation of Mia Platform
site_author: Mia Platform Team
copyright: Mia srl. All rights reserved.

nav:
- Home:
  - Mia Platform Docs: 'index.md'
  - Design Guidelines: 'guidelines/git_vademecum.md'
  - Custom Plugin: 'development_suite/plugin_baas_4.md'
  - CMS and Analytics: 'business_suite/api_console_configcms.md'
  - DevOps: 'development_suite/dev_ops_guide/business_continuity.md'
  - Release Notes: 'release_notes/apiconsole_releasenotes.md'
  - Info: 'info/version-policy.md'

- Guidelines:
    - GIT Vademecum: 'guidelines/git_vademecum.md'
    - REST API Vademecum: 'guidelines/rest_api.md'
    - API: 'guidelines/api.md'
    - Microservices Vademecum: 'guidelines/microservice_vademecum.md'
    - Docker Vademecum: 'guidelines/docker_vademecum.md'

- Runtime Suite:
    - Overview: 'runtime_suite/overview-runtime-suite.md'
    - Components Overview: 'runtime_suite/arc_components.md'
    - Components Configuration:
       - Configure Services Creation Templates: 'runtime_suite/templates_conf.md'
       - Configure Cron Service: 'runtime_suite/cron.md'
       - Configure Swagger Aggregator: 'runtime_suite/swagger_conf.md'
       - Configure Push Notifications: 'runtime_suite/push_notifications_platform_4.md'
       - iOS SDK: 'runtime_suite/sdk_ios.md'
       - Android SDK: 'runtime_suite/sdk_android.md'

- Development Suite:
  - Overview: 'development_suite/overview-dev-suite.md'
  - API Console / Microservices:
    - Access the API Console: 'development_suite/accedi_apiconsole.md'
    - Create a CRUD 5'min: 'development_suite/quick_rest_api.md'
    - Create Custom Microservices: 'development_suite/plugin_baas_4.md'
    - Expose and manage the safety of an apis: 'development_suite/esponi_api.md'
    - Manage your Microservices from the Api Console: 'development_suite/services.md'
    - Enrich your call with some Decorators: 'development_suite/decorators.md'
    - CRUD Section: 'development_suite/crud_advanced.md'
    - Advanced Section: 'development_suite/advanced_name_core.md'
    - Communication among Platorm 4 services: 'development_suite/communication_between_services_mp4.md'
    - Release your configurations: 'development_suite/deploy.md'

  - DevOps:
      - Business Continuity: 'development_suite/dev_ops_guide/business_continuity.md'
      - Disaster Recovery: 'development_suite/dev_ops_guide/disaster_recovery.md'
      - Autoscaling Pods: 'development_suite/dev_ops_guide/autoscaling.md'
      - Guidelines for logs: 'development_suite/dev_ops_guide/log.md'

- Business Suite:
  - Overview: 'business_suite/overview-business-suite.md'
  - CMS:
    - Use CMS: 'business_suite/guide_cms.md'
    - Configure CMS through API Console: 'business_suite/api_console_configcms.md'
    - Configure CMS .json file: 'business_suite/conf_cms.md'
    - Color CMS: 'business_suite/colorare_il_cms.md'
    - Update CMS: 'business_suite/update_cms.md'

  - Analytics:
    - Configure Analytics through API Console: 'business_suite/api_console_configanalytics.md'
    - Configure Analytics .json file: 'business_suite/conf_analytics.md'

- Release Notes:
    - Platform: 'release_notes/apiconsole_releasenotes.md'


- Info:
    - Version Policy: 'info/version-policy.md'
    - Open Source Software in Mia Platform: 'info/oss.md'
    - Audit Process: 'info/audit-process.md'
    - Subprocessor: 'info/subprocessor.md'
    - Installation Process: 'info/installation-process.md'
    - Bug Policy: 'info/bug-policy.md'



theme:
  name: 'material'
  logo: 'img/mia-platform-white.png'
  favicon: 'img/favicon.ico'
  language: 'it'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: 'true'
  extra:
    social:
      - type: globe
        link: https://www.mia-platform.eu/
      - type: linkedin
        link: https://www.linkedin.com/company/mia-platform/


google_analytics:
  - 'UA-122091925-1'
  - 'auto'
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
