site_name: Mia-Platform Docs
repo_url: http://git.makeitapp.eu/makeitapp-baas/mia-platform-doc
site_description: Documentazione della piattaforma Mia Platform
site_author: Mia Platform Team
copyright: Mia srl. Tutti i diritti riservati.
pages:
- Home: 'index.md'
- Getting started: 'getting_started/index.md'
- Developers:
  - Home: 'developer_guide/index.md'
  - API: 'developer_guide/api.md'
  - OpenAPI: 'developer_guide/openapi.md'
  - Creare un Plugin: 'developer_guide/plugin.md'
  - Creare un Tema: 'developer_guide/theme.md'
  - Users: 'developer_guide/users.md'
  - Files: 'developer_guide/files.md'
  - Push notifications: 'developer_guide/push_notifications.md'
  - Guida al Data Modeller: 'developer_guide/data_modeller.md'
  - Configurare il CMS: 'developer_guide/conf_cms.md'
  - Configurare il servizio di News: 'developer_guide/conf_news.md'
  - Configurare gli Analytics: 'developer_guide/conf_analytics.md'
  - iOS SDK: 'developer_guide/sdk_ios.md'
  - Android SDK: 'developer_guide/sdk_android.md'
- Users:
  - Home: 'user_guide_and_tools/index.md'
  - CMS: 'user_guide_and_tools/cms/index.md'
- Administrators:
  - Home: 'administrator_guide/index.md'
  - Backup: 'administrator_guide/backup.md'
  - Business Continuity: 'administrator_guide/business_continuity.md'
  - Disaster Recovery: 'administrator_guide/disaster_recovery.md'
- About:
  - Home: 'about/index.md'
  - Architecture: 'architecture/index.md'
  - Release Notes: 'release_notes/index.md'
  - Roadmap: 'roadmap/index.md'
#theme: readthedocs
