site_name: Mia-Platform Docs
repo_url: https://git.tools.mia-platform.eu/platform/documentations
site_description: Documentazione della piattaforma Mia Platform
site_author: Mia Platform Team
copyright: Mia srl. Tutti i diritti riservati.
pages:


- Home: 'index.md'

- Architecture:
    - Global vision: 'architecture/arc_overview.md'
    - Componenti: 'architecture/arc_components.md'
    - Overview: 'architecture/old_overview.md'

- Linee Guida Progettazione Mia:
    - GIT Vademecum: 'guidelines/git_vademecum.md'
    - API: 'guidelines/api.md'

- Developers Guide:
  - Home: 'developer_guide/index.md'
  - Creare un Plugin: 'developer_guide/plugin.md'
  - Creare un Tema: 'developer_guide/theme.md'
  - Users: 'developer_guide/users.md'
  - Cron: 'developer_guide/cron.md'
  - iOS SDK: 'developer_guide/sdk_ios.md'
  - Android SDK: 'developer_guide/sdk_android.md'
  - Plugin Piattaforma 4: 'developer_guide/plugin_baas_4.md'
  - Guida al Data Modeller: 'developer_guide/data_modeller.md'

- Configuration Manager:
  - Configurare il CMS: 'configurator/conf_cms.md'
  - Configurare gli Analytics: 'configurator/conf_analytics.md'

- DevOps:
  - Business Continuity: 'dev_ops_guide/business_continuity.md'
  - Pipe di Rilascio: 'dev_ops_guide/../developer_guide/pipelines.md'
  - Backup: 'dev_ops_guide/backup.md'
  - Disaster Recovery: 'dev_ops_guide/disaster_recovery.md'

- User Backoffice:
  - Home: 'user_guide_and_tools/index.md'
  - Api Console: 'user_guide_and_tools/api_console/guida_api_console.md'
  - CMS: 'user_guide_and_tools/cms/guide_cms.md'

- About:
  - Chi siamo: 'about/index.md'
  - Architecture: 'architecture/old_overview.md'
  - Release Notes: 'release_notes/index.md'
  - Contribute: 'about/contribute.md'
theme:
  name: 'material'
  logo: 'img/mia-platform-white.png'
  favicon: 'img/favicon.ico'
  language: 'it'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
extra:
  social:
    - type: globe
      link: https://www.mia-platform.eu/
    - type: linkedin
      link: https://www.linkedin.com/company/mia-platform/
  feature:
    tabs: true
google_analytics:
  - 'UA-122091925-1'
  - 'auto'
markdown_extensions:
  - admonition
