site_name: Mia-Platform Docs
repo_url: https://git.tools.mia-platform.eu/platform/documentations
site_description: Documentazione della piattaforma Mia Platform
site_author: Mia Platform Team
copyright: Mia srl. Tutti i diritti riservati.
pages:
- Home: 'index.md'
- Intro:
  - Getting started: 'getting_started/index.md'
  - Architecture:
    - Global vision: 'architecture/index.md'
    - Componenti: 'architecture/arc_components.md'
    - Logic: 'architecture/arc_logic.md'
    - Infrastructure: 'architecture/arc_infra.md'
- Developers:
  - Home: 'developer_guide/index.md'
  - API: 'developer_guide/api.md'
  - OpenAPI: 'developer_guide/openapi.md'
  - Creare un Plugin: 'developer_guide/plugin.md'
  - Creare un Tema: 'developer_guide/theme.md'
  - Users: 'developer_guide/users.md'
  - Files: 'developer_guide/files.md'
  - Push notifications: 'developer_guide/push_notifications.md'
  - Cron: 'developer_guide/cron.md'
  - Guida al Data Modeller: 'developer_guide/data_modeller.md'
  - Configurare il CMS: 'developer_guide/conf_cms.md'
  - Configurare il servizio di News: 'developer_guide/conf_news.md'
  - Configurare gli Analytics: 'developer_guide/conf_analytics.md'
  - iOS SDK: 'developer_guide/sdk_ios.md'
  - Android SDK: 'developer_guide/sdk_android.md'
  - Pipelines: 'developer_guide/pipelines.md'
  - Plugin Piattaforma 4: 'developer_guide/plugin_baas_4.md'
- DevOps:
  - GIT Vademecum: 'dev_ops_guide/git_vademecum.md'
- Users:
  - Home: 'user_guide_and_tools/index.md'
  - Api Console: 'user_guide_and_tools/api_console/guida_api_console.md'
  - CMS: 'user_guide_and_tools/cms/index.md'
- Administrators:
  - Home: 'administrator_guide/index.md'
  - Overview: 'administrator_guide/overview.md'
  - Pipe di Rilascio: 'administrator_guide/../developer_guide/pipelines.md'
  - Backup: 'administrator_guide/backup.md'
  - Business Continuity: 'administrator_guide/business_continuity.md'
  - Disaster Recovery: 'administrator_guide/disaster_recovery.md'
- About:
  - Chi siamo: 'about/index.md'
  - Architecture: 'architecture/index.md'
  - Release Notes: 'release_notes/index.md'
  - Contribute: 'about/contribute.md'
theme:
  name: 'material'
  logo: 'img/mia-platform-white.png'
  favicon: 'img/marchio.png'
