site_name: Mia-Platform Docs
repo_url: https://git.tools.mia-platform.eu/platform/documentations
site_description: Documentazione della piattaforma Mia Platform
site_author: Mia Platform Team
copyright: Mia srl. Tutti i diritti riservati.
pages:


- Home: 'index.md'

- Getting Started:
  - Dockerbox: '/getting_started/dockerbox/'
  - 5' minutes start - Hello World: '/getting_started/start-helloworld/'

- Architecture:
    - Global vision: '/architecture/arc_overview/'
    - Componenti: '/architecture/arc_components/'

- Linee Guida Progettazione Mia:
    - GIT Vademecum: '/guidelines/git_vademecum/'


- Developers Suite Tech:
  - Home: '/developer_guide/'
  - API: '/developer_guide/api/'
  - OpenAPI: '/developer_guide/openapi/'
  - Creare un Plugin: '/developer_guide/plugin/'
  - Creare un Tema: '/developer_guide/theme/'
  - Users: '/developer_guide/users/'
  - Cron: '/developer_guide/cron/'
  - iOS SDK: '/developer_guide/sdk_ios/'
  - Android SDK: '/developer_guide/sdk_android/'
  - Pipelines: '/developer_guide/pipelines/'
  - Plugin Piattaforma 4: '/developer_guide/plugin_baas_4/'
  - Files: '/developer_guide/files/'
  - Push notifications: '/developer_guide/push_notifications/'
  - Configurare il servizio di News: '/developer_guide/conf_news/'
  - Guida al Data Modeller: '/developer_guide/data_modeller/'

- Configuration Manager:
  - Configurare il CMS: '/configurator/conf_cms/'
  - Configurare gli Analytics: '/configurator/conf_analytics/'

- DevOps:
  - Business Continuity: '/dev_ops_guide/business_continuity/'

- User Backoffice:
  - Home: '/user_guide_and_tools/'
  - Api Console: '/user_guide_and_tools/api_console/guida_api_console/'
  - CMS: '/user_guide_and_tools/cms/'

- Administrators:
  - Home: '/administrator_guide/'
  - Overview: '/administrator_guide/overview/'
  - Pipe di Rilascio: '/administrator_guide/../developer_guide/pipelines/'
  - Backup: '/administrator_guide/backup/'
  - Disaster Recovery: '/administrator_guide/disaster_recovery/'

- About:
  - Chi siamo: '/about/'
  - Architecture: '/architecture/'
  - Release Notes: '/release_notes/'
  - Contribute: '/about/contribute/'
theme:
  name: 'material'
  logo: 'img/mia-platform-white.png'
  favicon: 'img/favicon.ico'
  language: 'it'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
extra:
  social:
    - type: globe
      link: https://www.mia-platform.eu/
    - type: linkedin
      link: https://www.linkedin.com/company/mia-platform/
  feature:
    tabs: true
google_analytics:
  - 'UA-122091925-1'
  - 'auto'
markdown_extensions:
  - admonition
