site_name: Mia-Platform Docs
repo_url: https://git.tools.mia-platform.eu/platform/documentations
site_description: Documentazione della piattaforma Mia Platform
site_author: Mia Platform Team
copyright: Mia srl. Tutti i diritti riservati.
pages:


- Home: 'index.md'

- Getting Started:

- Architecture:
    - Global vision: '/architecture/arc_overview/'
    - Componenti: '/architecture/arc_components/'
    - Overview: '/architecture/old_overview/'

- Linee Guida Progettazione Mia:
    - GIT Vademecum: '/guidelines/git_vademecum/'
    - API: '/guidelines/api/'

- Developers Guide:
  - Home: '/developer_guide/'
  - Creare un Plugin: '/developer_guide/plugin/'
  - Creare un Tema: '/developer_guide/theme/'
  - Users: '/developer_guide/users/'
  - Cron: '/developer_guide/cron/'
  - iOS SDK: '/developer_guide/sdk_ios/'
  - Android SDK: '/developer_guide/sdk_android/'
  - Plugin Piattaforma 4: '/developer_guide/plugin_baas_4/'
  - Guida al Data Modeller: '/developer_guide/data_modeller/'

- Configuration Manager:
  - Configurare il CMS: '/configurator/conf_cms/'
  - Configurare gli Analytics: '/configurator/conf_analytics/'

- DevOps:
  - Business Continuity: '/dev_ops_guide/business_continuity/'
  - Pipe di Rilascio: '/dev_ops_guide/../developer_guide/pipelines/'
  - Backup: '/dev_ops_guide/backup/'
  - Disaster Recovery: '/dev_ops_guide/disaster_recovery/'

- User Backoffice:
  - Home: '/user_guide_and_tools/'
  - Api Console: '/user_guide_and_tools/api_console/guida_api_console/'
  - CMS: '/user_guide_and_tools/cms/guide_cms/'

- About:
  - Chi siamo: '/about/'
  - Architecture: '/architecture/'
  - Release Notes: '/release_notes/'
  - Contribute: '/about/contribute/'
theme:
  name: 'material'
  logo: 'img/mia-platform-white.png'
  favicon: 'img/favicon.ico'
  language: 'it'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
extra:
  social:
    - type: globe
      link: https://www.mia-platform.eu/
    - type: linkedin
      link: https://www.linkedin.com/company/mia-platform/
  feature:
    tabs: true
google_analytics:
  - 'UA-122091925-1'
  - 'auto'
markdown_extensions:
  - admonition
