site_name: Mia-Platform Docs
site_description: Platform documentation of Mia Platform
site_author: Mia Platform Team
copyright: Mia srl. All rights reserved.
plugins:
  - search
  - monorepo
  - minify:
      minify_html: true

nav:
- Home:
  - Mia Platform Docs: 'index.md'
  - Getting Started: 'getting_started/quickstart.md'
  - Design Guidelines: 'dev_ops_guide/git_vademecum.md'
  - Custom Plugin: 'development_suite/api-console/api-design/plugin_baas_4.md'
  - CMS and Analytics: 'business_suite/overview-business-suite.md'
  - DevOps: 'development_suite/monitoring-dashboard/dev_ops_guide/business_continuity.md'
  - Release Notes: 'release_notes/platform_releasenotes.md'
  - Info: 'info/version-policy.md'

- DevOps Console:
  - Overview: 'development_suite/overview-dev-suite.md'
  - Permission Management: 'development_suite/Console levels and permits management.md'
  - Set Up Infrastructure:
    - Configure Auth0: 'development_suite/set-up-infrastructure/auth-0-setup.md'
    - Manage Environment Variables: 'development_suite/set-up-infrastructure/env-var.md'
    - Create Project: 'development_suite/set-up-infrastructure/create-project.md'
  - Design:
    - QuickStart: 'development_suite/api-console/api-design/quick_rest_api.md'
    - CRUD: 'development_suite/api-console/api-design/crud_advanced.md'
    - Services:
       - Manage your Microservices from the Dev Console: 'development_suite/api-console/api-design/services.md'
       - Marketplace: 'development_suite/api-console/api-design/marketplace.md'
       - Microservice from template - Get started: 'development_suite/api-console/api-design/custom_microservice_get_started.md'
       - Create a Node Custom Microservices: 'development_suite/api-console/api-design/plugin_baas_4.md'
       - Add a Microservices Template : 'development_suite/api-console/api-design/templates_conf.md'
    - CronJob:
        - Create and Manage Cronjob: 'development_suite/api-console/api-design/jobs-cronjob.md'

    - PRE/POST: 'development_suite/api-console/api-design/decorators.md'
    - Endpoints: 'development_suite/api-console/api-design/esponi_api.md'
    - CMS and Analytics:
       - Configure CMS: 'development_suite/api-console/api-design/api_console_configcms.md'
       - Configure Analytics: 'development_suite/api-console/api-design/api_console_configanalytics.md'
    - Advanced Section:
      - API Gateway:
        -  Create config map: 'development_suite/api-console/advanced-section/api-gateway/config-map.md'
        -  Request Size: 'development_suite/api-console/advanced-section/api-gateway/request-size.md'
      - Dev Console Config:
        - Change the name of Core Microservices: 'development_suite/api-console/advanced-section/dev-console-config/advanced_name_core.md'
        - How to change the number of replicas: 'development_suite/api-console/advanced-section/dev-console-config/replicas.md'
      - Authorization Service:
        - How to configure: 'development_suite/api-console/advanced-section/authorization-service/configuration.md'
      - Auth0 Client:
        - How to configure: 'development_suite/api-console/advanced-section/auth0-client/configuration.md'
    - How to enable Auth0: 'development_suite/api-console/api-design/how_to_enable_auth0.md'
  - Test & Debug:
    - Debug a Microservice: 'development_suite/debugging/telepresence.md'
  - Deploy:
    - Release your configurations: 'development_suite/deploy/deploy.md'
    - Configure a custom Webhook: 'development_suite/deploy/configuration.md'

  - Monitoring:
      - Monitor your applications: 'development_suite/monitoring/monitoring.md'
      - Configure your Monitoring Area: 'development_suite/monitoring/configuration.md'

  - API Portal:
    - APIs Documentation: 'development_suite/api-portal/api-documentations.md'
    - Configure Swagger Aggregator: 'development_suite/api-portal/swagger_conf.md'

- Microservices Ecosystem:
    - Overview: 'runtime_suite/overview-runtime-suite.md'
    - API & Microservice Ecosystem:
       - API Gateway: 'runtime_suite/api-gateway.md'
       - Microservice Gateway: 'runtime_suite/microservice-gateway.md'
       - BaaS:
         - Crud: 'runtime_suite/crud-service.md'
         - Static File Hosting: 'runtime_suite/static-file-service.md'
         - File Manager Service:
            - Usage: 'runtime_suite/files-service/usage.md'
            - Configuration: 'runtime_suite/files-service/configuration.md'
         - Notifications:
           - Push Notifications: 'runtime_suite/push_notifications_platform_4.md'
           - Mail Service: 'runtime_suite/mail-notification.md'
           - Notifcation Manager: 'runtime_suite/notifications-manager.md'
         - iOS SDK: 'runtime_suite/sdk_ios.md'
         - Android SDK: 'runtime_suite/sdk_android.md'
         - PDF Service: 'runtime_suite/pdf-service.md'
         - Doctor Service:
           - Services health: 'runtime_suite/doctor-service/services_status.md'
           - Configure Doctor Service: 'runtime_suite/doctor-service/configure_doctor_service.md'

       - Data Management:
         - SQL Generic Reader: 'runtime_suite/sql-reader.md'
         - CQRS/Event Source Management: 'runtime_suite/event-source-management.md'
         - Secure Data Exchange Service: 'runtime_suite/secure-data-exchange-service.md'
         - Soap To Rest: 'runtime_suite/soap-to-rest.md'
         - Mongo 2 Kafka: 'runtime_suite/mongo2kafka.md'
       - API Automation:
         - Cronjobs Microservices: 'runtime_suite/cron.md'

       - MongoDB Reader:
         - Configuration: 'runtime_suite/mongodb-reader/service-configuration.md'
         - Filters: 'runtime_suite/mongodb-reader/filters.md'
         - ACL: 'runtime_suite/mongodb-reader/aclrows.md'
       - Timer Service:
         - Introduction: 'runtime_suite/timer-service/index.md'
         - Configuration: 'runtime_suite/timer-service/configuration.md'
         - Usage: 'runtime_suite/timer-service/usage.md'
    - Privacy & Security:
      - Access Management:
        - Auth Service: 'runtime_suite/auth-service.md'
        - Users Profile: 'runtime_suite/user-service.md'
        - ACL Service: 'runtime_suite/acl-service.md'
        - Session Manager: 'runtime_suite/session-manager.md'
        - Auth0 Client:
          - How to use: 'runtime_suite/auth0-client/how_to_use.md'
          - Configuration: 'runtime_suite/auth0-client/configuration.md'
        - Authorization Service:
          - How to use: 'runtime_suite/authorization-service/how_to_use.md'
          - Configuration: 'runtime_suite/authorization-service/configuration.md'

- API Management & Headless CMS:
  - Overview: 'business_suite/overview-business-suite.md'
  - CMS:
    - Use CMS: 'business_suite/guide_cms.md'
    - Configure CMS through Dev Console: 'development_suite/api-console/api-design/api_console_configcms.md'
    - Configure CMS .json file: 'business_suite/conf_cms.md'
    - Color CMS: 'business_suite/colorare_il_cms.md'
    - Update CMS: 'business_suite/update_cms.md'
    - Integrate custom frontends into the CMS: 'business_suite/custom-frontends-integration-CMS.md'

  - Analytics:
    - Configure Analytics through Dev Console: 'development_suite/api-console/api-design/api_console_configanalytics.md'
    - Configure Analytics .json file: 'business_suite/conf_analytics.md'

  - Data Visualization:
    - Configure Data Visualization Dashboard: 'business_suite/data-visualization.md'

- Fast Data:
    - Overview: 'fast_data/overview.md'

- Release Notes:
    - Platform:
      - Platform v5:
        - Platform v5.9: 'release_notes/platform_5-9-0_releasenote.md'     
        - Platform v5.8: 'release_notes/platform_5-8-0_releasenotes.md'
        - Platform v5.7: 'release_notes/platform_5-7-0_releasenotes.md'
        - Platform v5.6: 'release_notes/platform_5-6-0_releasenotes.md'
        - Platform v5.5: 'release_notes/platform_5-5-0_releasenotes.md'
        - Platform v5.4: 'release_notes/platform_5-4-0_releasenotes.md'
        - Platform v5.3: 'release_notes/platform_5-3-0_releasenotes.md'
        - Platform v5.2: 'release_notes/platform_5-2-0_releasenotes.md'
        - Platform v5.1: 'release_notes/platform_5-1-0_releasenotes.md'
        - Platform v5.0: 'release_notes/platform_5-0-0_releasenotes.md'
      - Platform previous versions: 'release_notes/platform_releasenotes.md'
    - Support Policy: 'release_notes/support-policy.md'

- Guidelines:
    - Glossary: 'guidelines/glossary.md'
    - GIT Vademecum: 'dev_ops_guide/git_vademecum.md'
    - REST API Vademecum: 'guidelines/rest_api.md'
    - Microservices Vademecum: 'guidelines/microservice_vademecum.md'
    - Communication among Microservices: 'guidelines/communication_between_services_mp4.md'
    - Docker Vademecum: 'guidelines/docker_vademecum.md'
    - Business Continuity: 'development_suite/monitoring-dashboard/dev_ops_guide/business_continuity.md'
    - Disaster Recovery: 'development_suite/monitoring-dashboard/dev_ops_guide/disaster_recovery.md'
    - Autoscaling Pods: 'development_suite/monitoring-dashboard/dev_ops_guide/autoscaling.md'
    - Guidelines for logs: 'development_suite/monitoring-dashboard/dev_ops_guide/log.md'

- Info:
    - Version Policy: 'info/version-policy.md'
    - Supported Browsers: 'info/supported-browsers.md'
    - Open Source Software in Mia Platform: 'info/oss.md'
    - Audit Process: 'info/audit-process.md'
    - Subprocessor: 'info/subprocessor.md'
    - Installation Process: 'info/installation-process.md'
    - Bug Policy: 'info/bug-policy.md'
    - Migrate from v4 to v5: 'info/migrate-from-v4-to-v5.md'

- Previous version:
    - v4: '!include ./previous_versions/v4/mkdocs.yml'

theme:
  name: 'material'
  logo: 'img/mia-platform-white.png'
  favicon: 'img/favicon.ico'
  language: 'it'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - tabs
    - instant

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.mia-platform.eu/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mia-platform/

google_analytics:
  - 'UA-122091925-1'
  - 'auto'

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js
