site_name: Mia-Platform Docs
repo_url: https://git.tools.mia-platform.eu/platform/documentations
site_description: Documentazione della piattaforma Mia Platform
site_author: Mia Platform Team
copyright: Mia srl. Tutti i diritti riservati.

nav:
- Home:
  - Mia Platform Docs: 'index.md'
  - Linee Guida Progettazione: 'guidelines/git_vademecum.md'
  - Custom Plugin: 'development_suite/plugin_baas_4.md'
  - CMS e Analitici: 'business_suite/api_console_configcms.md'
  - DevOps: 'development_suite/dev_ops_guide/business_continuity.md'
  - Release Note: 'release_notes/apiconsole_releasenotes.md'
  - Info: 'info/version-policy.md'

- Linee Guida:
    - GIT Vademecum: 'guidelines/git_vademecum.md'
    - REST API Vademecum: 'guidelines/rest_api.md'
    - API: 'guidelines/api.md'
    - Microservizi Vademecum: 'guidelines/microservice_vademecum.md'
    - Docker Vademecum: 'guidelines/docker_vademecum.md'

- Runtime Suite:
    - Overview of all the components: 'runtime_suite/arc_components.md'
    - Configure the components:
       - Configure templates for creating services: 'runtime_suite/templates_conf.md'
       - Configure Cron Service: 'runtime_suite/cron.md'
       - Configure Swagger Aggregator: 'runtime_suite/swagger_conf.md'
       - Configure Push Notifications: 'runtime_suite/push_notifications_platform_4.md'
       - iOS SDK: 'runtime_suite/sdk_ios.md'
       - Android SDK: 'runtime_suite/sdk_android.md'

- Development Suite:
  - API Console e Microservizi:
    - Accedi all'API Console: 'development_suite/accedi_apiconsole.md'
    - Crea un CRUD 5'min: 'development_suite/quick_rest_api.md'
    - Crea un Custom Microservices: 'development_suite/plugin_baas_4.md'
    - Esponi un'API e configura la sua sicurezza: 'development_suite/esponi_api.md'
    - Gestisci i tuoi Microservizi dall'Api Console: 'development_suite/services.md'
    - Arricchisci la tua chiamata con dei Decoratori: 'development_suite/decorators.md'
    - CRUD - Sezione Avanzata: 'development_suite/crud_advanced.md'
    - Comunicazione fra servizi nella Piattaforma 4: 'development_suite/communication_between_services_mp4.md'
    - Rilascia le tue configurazioni: 'development_suite/deploy.md'

  - DevOps:
      - Business Continuity: 'development_suite/dev_ops_guide/business_continuity.md'
      - Disaster Recovery: 'development_suite/dev_ops_guide/disaster_recovery.md'
      - Autoscaling Pods: 'development_suite/dev_ops_guide/autoscaling.md'
      - Linee guida per i log: 'development_suite/dev_ops_guide/log.md'

- Business Suite:
  - CMS:
    - Utilizzare il CMS: 'business_suite/guide_cms.md'
    - Configurare il CMS con l'API Console: 'business_suite/api_console_configcms.md'
    - Configurare il file .json del CMS: 'business_suite/conf_cms.md'
    - Colorare il CMS: 'business_suite/colorare_il_cms.md'
    - Aggiornare la versione del CMS: 'business_suite/update_cms.md'

  - Analitici:
    - Configurare gli Analytics con l'API Console: 'business_suite/api_console_configanalytics.md'
    - Configurare il file .json degli Analytics: 'business_suite/conf_analytics.md'

- Release Notes:
    - Piattaforma: 'release_notes/apiconsole_releasenotes.md'


- Info:
    - Version Policy: 'info/version-policy.md'
    - Open Source Software in Mia Platform: 'info/oss.md'
    - Subprocessor: 'info/subprocessor.md'
    - Audit Process: 'info/audit-process.md'
    - Installation Process: 'info/installation-process.md'


theme:
  name: 'material'
  logo: 'img/mia-platform-white.png'
  favicon: 'img/favicon.ico'
  language: 'it'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: 'true'
  extra:
    social:
      - type: globe
        link: https://www.mia-platform.eu/
      - type: linkedin
        link: https://www.linkedin.com/company/mia-platform/


google_analytics:
  - 'UA-122091925-1'
  - 'auto'
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
