site_name: Mia-Platform Docs
repo_url: https://git.tools.mia-platform.eu/platform/documentations
site_description: Documentazione della piattaforma Mia Platform
site_author: Mia Platform Team
copyright: Mia srl. Tutti i diritti riservati.
pages:


- Home: 'index.md'

- Getting Started:
  - Dockerbox: 'getting_started/dockerbox.md'
  - 5' minutes start - Hello World: 'getting_started/start-helloworld.md'


- Architecture:
    - Global vision: 'architecture/arc_overview.md'
    - Componenti: 'architecture/arc_components.md'


- Developers Suite Tech:
  - Home: 'developer_guide/index.md'
  - API: 'developer_guide/api.md'
  - OpenAPI: '/developer_guide/openapi/'
  - Creare un Plugin: './developer_guide/plugin.md'
  - Creare un Tema: 'developer_guide/theme.md'
  - Users: 'developer_guide/users.md'
  - Cron: 'developer_guide/cron.md'
  - iOS SDK: 'developer_guide/sdk_ios.md'
  - Android SDK: 'developer_guide/sdk_android.md'
  - Pipelines: 'developer_guide/pipelines.md'
  - Plugin Piattaforma 4: 'developer_guide/plugin_baas_4.md'

- Developers Suite Business:
  - Files: 'developer_guide/files.md'
  - Push notifications: 'developer_guide/push_notifications.md'
  - Configurare il CMS: 'developer_guide/conf_cms.md'
  - Configurare il servizio di News: 'developer_guide/conf_news.md'
  - Configurare gli Analytics: 'developer_guide/conf_analytics.md'
  - Guida al Data Modeller: 'developer_guide/data_modeller.md'

- DevOps:
  - GIT Vademecum: 'dev_ops_guide/git_vademecum.md'
  - Business Continuity: 'dev_ops_guide/business_continuity.md'

- Users:
  - Home: 'user_guide_and_tools/index.md'
  - Api Console: 'user_guide_and_tools/api_console/guida_api_console.md'
  - CMS: 'user_guide_and_tools/cms/index.md'

- Administrators:
  - Home: 'administrator_guide/index.md'
  - Overview: 'administrator_guide/overview.md'
  - Pipe di Rilascio: 'administrator_guide/../developer_guide/pipelines.md'
  - Backup: 'administrator_guide/backup.md'
  - Disaster Recovery: 'administrator_guide/disaster_recovery.md'

- About:
  - Chi siamo: 'about/index.md'
  - Architecture: 'architecture/index.md'
  - Release Notes: 'release_notes/index.md'
  - Contribute: 'about/contribute.md'
theme:
  name: 'material'
  logo: 'img/mia-platform-white.png'
  favicon: 'img/favicon.ico'
  language: 'it'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
extra:
  social:
    - type: globe
      link: https://www.mia-platform.eu/
    - type: linkedin
      link: https://www.linkedin.com/company/mia-platform/
  feature:
    tabs: true
google_analytics:
  - 'UA-122091925-1'
  - 'auto'
markdown_extensions:
  - admonition
