apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: documentation-site
  labels:
    component: documentation-site
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    component: documentation-site
