apiVersion: v1
kind: Service
metadata:
  name: "documentation-site-next"
  labels:
    component: "documentation-site-next"
spec:
  type: "ClusterIP"
  ports:
    - name: "http"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    component: "documentation-site-next"
